name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: hello_world
        run: echo Hello, world!
        shell: powershell
      - name: install_navcontainerhelper
        run: Install-Module NavContainerHelper -Force
        shell: powershell
      - name: get_module_navcontainerhelper
        run: Get-Module NavContainerHelper
        shell: powershell
        
