name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1    
      - name: Install NavContainerHelper
        run: Install-Module NavContainerHelper -Force
        shell: powershell
      - name: Get module NavContainerHelper
        run: Get-Module NavContainerHelper
        shell: powershell
      - name: List workspace
        run: ls $Env:GITHUB_WORKSPACE
        shell: powershell
      - name: Set up Business Central container
        env:
          USERNAME: ${{ secrets.BA_USERNAME }}
          PASSWORD: ${{ secrets.BA_PASSWORD }}
        run: >
          New-NavContainer 
          -accept_eula 
          -containerName bcdev 
          -imageName mcr.microsoft.com/businesscentral/onprem:latest 
          -useBestContainerOS 
          -alwaysPull 
          -auth NavUserPassword 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -updateHosts 
          -doNotExportObjectsToText 
          -enableSymbolLoading
          -additionalParameters --volume $Env:GITHUB_WORKSPACE:C:\Agent
        shell: powershell
      - name: Build application
        env:
          USERNAME: ${{ secrets.BA_USERNAME }}
          PASSWORD: ${{ secrets.BA_PASSWORD }}    
        run: >
          Compile-AppInBCContainer 
          -containerName bcdev 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -appProjectFolder $Env:GITHUB_WORKSPACE
        shell: powershell
